# Docker Compose para desenvolvimento
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - vendor:/var/www/html/vendor
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=null
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync

volumes:
  vendor:
    driver: local