global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'laravel'
    static_configs:
      - targets: ['app:80']
    metrics_path: /metrics

  - job_name: 'nova-api'
    static_configs:
      - targets: ['nova-api:3001']
    metrics_path: /metrics

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics